# Created using wingetcreate

PackageIdentifier: OracleCorporation.OracleVMVirtualBox
PackageVersion: 6.1.22.144080
PackageLocale: en-US
Publisher: Oracle Corporation
PackageName: virtualbox
License: Copyright (C) 2009-2021 Oracle Corporation
ShortDescription: VirtualBox
ManifestType: defaultLocale
ManifestVersion: 1.0.0
