# Created using wingetcreate

PackageIdentifier: Discord.Discord
PackageVersion: 1.0.9002
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: neutral
  InstallerType: exe
  Scope: machine
  InstallerUrl: https://dl.discordapp.net/distro/app/stable/win/x86/1.0.9002/DiscordSetup.exe
  InstallerSha256: E825CF8E0B4DB9797CA9E57191B01AAB0C06536A24D08EC0A4767B5248A8526F
  InstallerSwitches:
    Silent: /s
    SilentWithProgress: /s
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
